### ISSUE TITLE
Service not responding/unstable?

### ISSUE THREAD

**Issue by sigven** [chembl/chembl_webservices_py3#1]
Hi,

I have been using the API successfully for some time now, but I am now experiencing a lack of response, particularly when searching molecule chembl id using a query string, i.e.:

https://www.ebi.ac.uk/chembl/api/data/chembl_id_lookup?q=vemurafenib

There is however a lack of response now, it seems? I get resultsets on some queries, but I see no pattern as to when there is no response and when there is response. I have also tried the Python web service client, but that did not help too much. 

Is there anything I should do differently or other things I am unaware of in order to access the data through a web service?

regards,
Sigve

**Comment by juanfmx2** [comment]
Hi, we where updating the web  services and this should be fixed now. You should use the search endpoint inside to use the q parameter:

https://www.ebi.ac.uk/chembl/api/data/chembl_id_lookup/search?q=vemurafenib
